matthew6project/thirtyone

app/assets/stylesheets/people.css.scss, app/controllers/people_controller.rb, app/views/people/show.html.erb
=> Show person

app/assets/stylesheets/scaffolds.css.scss, app/views/layouts/application.html.erb
Styled the error and notice notifications (see #44 )
=> styled the error and notice notifications

.gitignore, app/assets/javascripts/people.js, app/controllers/people_controller.rb, app/views/people/_search_results.html.erb, app/views/people/index.html.erb, config/routes.rb
Fixes #48 and #49: Also ignores DS_Store. :+1:
=> Make Add Person Button Copy Name Values

app/assets/stylesheets/people.css.scss, app/controllers/people_controller.rb, app/controllers/users_controller.rb, app/models/person.rb, app/models/role.rb, app/models/user.rb, app/views/people/_form.html.erb, app/views/users/sessions/new.html.erb, db/migrate/20150203030249_add_person_to_users.rb, db/migrate/20150304013524_add_email_to_people.rb, db/schema.rb, db/seeds.rb
This is a rough working copy of the code to associate users with the person model and manage their roles and login information.   It also includes a default login with username/password admin/admin.
I'm continuing to work on this feature but lack of connectivity between the user and the person model was holding up other code, so this is just to get it out there for now.
=> Tie users to person (Rough Working Copy)

app/assets/javascripts/work_schedule_form.js, app/assets/stylesheets/work_schedule.css.scss, app/controllers/work_schedule_controller.rb, app/views/work_schedule/_form.html.erb
* Fixes some bugs with flash messages not disappearing until second redirect.
* Fixed submitting a work schedule without changing the time (date in form was in wrong format).
* Cancel no longer goes back because going back after submitting an invalid staff name would return you back to the new work schedule page. Cancel now goes back to the index of work schedule.
=> Fixes #57 and #58

app/views/people/show.html.erb
Converted some &lt;p&gt; tags to &lt;div&gt; using the foundation grid
=> Removed hard coded email on person page

app/views/static_pages/_topnav.html.erb
Changed "My Account" nav link for #50
=> Updated My Account link to go to edit current/active person

db/seeds.rb
Fixes a crash on the TopNav code for the admin user
=> #81 Modifies the database seed file to tie the admin user to a person

app/controllers/people_controller.rb
Also reorganized the code to remove duplicate update logic
=> Validate that all users have an email and that the email is valid

app/controllers/users_controller.rb, db/migrate/20150502005012_remove_name_from_users.rb, db/schema.rb
A users name is stored in the person relationship.  Fixes #84.
=> (#84) Removed name column from user model

app/controllers/users_controller.rb, app/models/user.rb, app/views/roles/_permissions.html.erb, config/initializers/permissions.rb, db/seeds.rb
See #60: Admin permission. Also a helper method on user to check if a user has a permission.
=> Admin permission

app/assets/stylesheets/people.css.scss, app/controllers/people_controller.rb, app/views/household/_show.html.erb, app/views/people/show.html.erb
Re-formatted show person and added the list of roles for the person/user. Also fixed a little formatting in show household
Fixes #87
=> Reformatted show person and added roles.

app/models/user.rb, app/views/people/_form.html.erb
Disable other role checkboxes when the admin role checkbox is checked.
Fixes #102.
=> Disable checkboxes when admin checkbox checked

app/assets/stylesheets/scaffolds.css.scss, app/models/person.rb
=> (#83) Make first and last name required

app/views/people/index.html.erb, app/views/static_pages/_topnav.html.erb
=> Fix partials

app/controllers/roles_controller.rb, app/views/roles/bulk_assign_new.html.erb, config/routes.rb
See #60: Adding bulk assignment of users to roles.
=> Bulk roles assignment

app/controllers/roles_controller.rb, app/policies/role_policy.rb, db/seeds.rb
See #60: Adding in permission controls for the roles pages.
=> Add policy for roles pages.

app/models/user.rb, app/policies/role_policy.rb, app/views/static_pages/_topnav.html.erb
Rename the permission check method.
=> Rename user permission check

app/views/people/show.html.erb
=> (#110) Fixed a crash on the show person page when the person is not a user

app/assets/javascripts/people.js, app/controllers/people_controller.rb, app/controllers/users_controller.rb, app/views/people/_form.html.erb, app/views/people/_form_page_title.erb, app/views/people/_onkeyup_search.erb, app/views/people/index.html.erb, app/views/users/_form_page_title.erb, app/views/users/_onkeyup_search.erb
- The Users top nav uses the same view as the people search, but it only displays people who are also users
- The dynamic search has been updated to also be able to search for only users by firstname and lastname
- When on the users topnav, if you click the `+ New User` button it will render the people form, but
with the "Allow person to login" radio button already selected.
Implements #67
=> (67) Added functionality to Users top nav

app/views/static_pages/_topnav.html.erb
We aren't implementing a full featured inventory system in version 1.0
but we do want to release one eventually, so just commenting this code
for now.
=> (#75) Commented put the Inventory item from the topnav.

app/models/address.rb, app/views/household/_new.html.erb
=> Auto select most used state in the database when creating new addresses

app/controllers/people_controller.rb, app/models/address.rb, app/models/household.rb, app/models/person.rb, app/models/user.rb, app/views/people/_form.html.erb, app/views/people/show.html.erb
This commit includes the addition of validations for person, person.household
and person.household.address.  It also provides better error messages for the user
rather then just letting the exception error messages bubble up.
Fixes #126, Fixes #88
=> Provide better error messages when validations fail on the person model

app/controllers/people_controller.rb, app/policies/person_policy.rb
Create the pundit permission policies for viewing and editing people
Fixes #69
=> Create permission policy for people

app/controllers/visits_controller.rb, app/models/person.rb, app/models/visit.rb, app/views/people/show.html.erb, app/views/visits/_form.html.erb, app/views/visits/show.html.erb
The visit page was using old schema information where it was trying to get host names from the user model.  All first/last name information is now stored on the person model only.
I was also relying on some of the old event-calendar code.
=> Fix visits page

Gemfile, Gemfile.lock
This gem filters out all of the verbose GET calls that show up in the console log
when running the rails embedded server
=> Added quiet_assets gem

app/assets/javascripts/local_resources_form.js, app/controllers/people_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, db/schema.rb
Send new account instructions when making a new account.
=> Send new account instructions

app/models/household.rb, app/models/person.rb
Changed the relationship between household and person from has_one to belongs_to
=> Fixes #168 - Head of Household logic not working

app/assets/javascripts/app.people.js, app/views/people/_onkeyup_search.erb, app/views/users/_onkeyup_search.erb
During refactor into the app.x namespace, some references were missed.
I fixed all the references and removed some unused JS.
=> Fix the Person/User Search

Gemfile.lock, app/assets/javascripts/app.work_schedule.js, app/assets/javascripts/application.js, app/views/work_schedule/_form.html.erb
- Reworked work schedule javascript into the new format …
- Updated ionRangeSlider to pull in the fix an issue: IonDen/ion.rangeSlider#310
- Fixed a bug where ending a schedule at midnight caused the range slider to display incorrectly
=> Misc fixes for work schedule

app/assets/javascripts/app.calendar.js, app/assets/javascripts/application.js
Refactor calendar JS to use new format.
=> Refactored calendar JS to use new format.

db/seeds.rb
The db:seeds file was failing to find a ROLE with permission PERM_RO_USER.
=> Fixing db:seeds

app/controllers/event_controller.rb, app/controllers/inventory_items_controller.rb, app/controllers/inventory_order_items_controller.rb, app/controllers/inventory_orders_controller.rb, app/controllers/inventory_stock_records_controller.rb, app/controllers/local_resource_categories_controller.rb, app/controllers/local_resources_controller.rb, app/controllers/user_roles_controller.rb, app/controllers/users_controller.rb, app/controllers/visits_controller.rb, app/controllers/work_schedule_controller.rb, app/models/address.rb
=> Ft ensure use of strong params

app/controllers/roles_controller.rb, app/models/role.rb
This achieves this by the following:
* create method to validate submissions for bulk_assign_create
* create set_role_permission to handle role assignment for update and create action
* add validation for presence of name in the role model
* refactor create action and have it use the set_role_permission method
* refactor update action and have it use the set_role_permission method
* minor fixes and rewirtes
=> Refactor Roles Controller

app/views/people/_form.html.erb
=> Added a cancel button to create person page

app/assets/javascripts/app.local_resources.js, app/assets/stylesheets/local_resources.css.scss, app/assets/stylesheets/people.css.scss, app/controllers/local_resources_controller.rb, app/policies/local_resource_policy.rb, app/utilities/local_resource_search.rb, app/views/local_resources/_search_results.html.erb, app/views/local_resources/index.html.erb, config/routes.rb, spec/controllers/local_resources_controller_spec.rb
=> Add local resource filtering

app/assets/javascripts/app.household.js, app/controllers/household_controller.rb, app/models/address.rb, app/models/household.rb, app/policies/household_policy.rb, app/views/household/_merge_household_address.html.erb, app/views/household/_merge_household_members.html.erb, app/views/household/_merge_household_name.html.erb, app/views/household/_merge_select_head_of_household.html.erb, app/views/household/_search.html.erb, app/views/household/_search_results.html.erb, app/views/household/merge.html.erb, app/views/household/merge_select_fields.html.erb, app/views/household/show.html.erb, config/routes.rb, db/seeds.rb, spec/controllers/household_controller_spec.rb
=> Add Household Merge Page

app/assets/stylesheets/main.css.scss, app/controllers/visits_controller.rb, app/models/visit.rb, app/views/visits/_form.html.erb, app/views/visits/_visit.html.erb, app/views/visits/index.html.erb
=> Visit index

app/controllers/household_controller.rb, app/models/household.rb, app/policies/household_policy.rb, app/views/household/show.html.erb, db/migrate/20160604003857_add_deleted_at_to_household.rb, db/schema.rb
Enables deleting households and uses paranoia
Fixes #216
=> Allow deleting households

app/views/household/_edit.html.erb, app/views/people/_form.html.erb
Closes #213 
I think these are all the required fields, I was guessing a bit on the household since that functionality is still broke, but I am pretty positive that these are the fields that are required still. 😬
=> Label field require

app/controllers/visits_controller.rb, app/models/visit.rb, app/views/visits/index.html.erb
=> Allow user to show all or just active visits

app/assets/stylesheets/foundation_and_overrides.scss, app/views/household/_select.html.erb, app/views/inventory_items/_edit.html.erb, app/views/inventory_items/_new.html.erb, app/views/people/_form.html.erb, app/views/people/show.html.erb, app/views/roles/index.html.erb, app/views/users/_form.html.erb, app/views/users/show.html.erb, app/views/work_schedule/_user_search_results.html.erb
Closes #180 
Closes #179 
These changes are just to standardize the navigation buttons to be medium.  I did not change certain buttons like `Resend Confirmation Email`
The padding on the medium sized buttons also has been modified.
=> Changed the buttons from tiny to medium

Gemfile, Gemfile.lock, app/controllers/people_controller.rb, app/controllers/users_controller.rb, app/models/person.rb, app/models/user.rb, app/policies/person_policy.rb, app/policies/user_policy.rb, app/utilities/people_submission_validator.rb, app/views/people/_form.html.erb, app/views/people/show.html.erb, app/views/static_pages/_topnav.html.erb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, app/views/users/email/confirm_email_change.html.erb, app/views/users/mailer/confirmation_instructions.html.erb, config/initializers/filter_parameter_logging.rb, config/routes.rb, coverage/.last_run.json
=> Split User and Person Edit Pages

app/views/users/_form.html.erb
Autofocus is already set on the password field
=> Removed autofocus from password confirmation
